services:
  - type: web
    name: job-board-api
    env: node
    region: singapore
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://altamashahmadajaz2:Test123@cluster0.2wylgjh.mongodb.net/job-board?retryWrites=true&w=majority
      - key: REDIS_URL
        value: redis://default:9Dst48U4sBjJC9w4wSHBZVmqRm5UinE3@redis-11515.crce182.ap-south-1-1.ec2.redns.redis-cloud.com:11515
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://job-board-kappa-murex.vercel.app 